#server:
#  port: 9070
zuul:
  routes:
    #这里没有使用服务发现组件，所以将服务服务地址写死
    api:
      url: http://localhost:9070  #网关地址

  #zuul.sensitiveHeaders设置为空，代表不过滤任何Header信息，Header会向下转发
  sensitive-headers:


spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
    # password:
  application:
    name: gateway

